node {
   // Mark the code checkout 'stage'....
   stage 'Checkout'

   // Get some code from a GitHub repository
   git url: 'https://github.com/spring-projects/spring-petclinic.git'
   sh "git rev-parse --short HEAD > .git/commit-id"                        
   commit_id = readFile('.git/commit-id').trim()

   // Get the maven tool.
   // ** NOTE: This 'M3' maven tool must be configured
   // **       in the global configuration.           
   def mvnHome = tool 'M3'

   // Mark the code build 'stage'....
   stage 'Build'
   // Run the maven build
   sh "${mvnHome}/bin/mvn -Dmaven.test.failure.ignore clean package"
   step([$class: 'JUnitResultArchiver', testResults: '**/target/surefire-reports/TEST-*.xml'])
   
   stage 'Deploy'
   sh "apc target pjmdevaws2.apcera-platform.io"
   sh "apc login --app-auth"
   sh "apc app create petclinic-${commit_id} --path target --batch --start"
}
